spring:
  application:
    name: open-in-view-lab

  threads:
    virtual:
      enabled: true

  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        generate_statistics: true
        format_sql: true
    show-sql: false

  datasource:
    hikari:
      maximum-pool-size: 5
      minimum-idle: 2
      connection-timeout: 3000

logging:
  level:
    org.hibernate.stat: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE
